/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.R_JABATAN_KOMITE_SUB_KOMITE ADD
	NOTULEN char(1) NULL
GO
ALTER TABLE dbo.R_JABATAN_KOMITE_SUB_KOMITE ADD CONSTRAINT
	DF_R_JABATAN_KOMITE_SUB_KOMITE_NOTULEN DEFAULT 0 FOR NOTULEN
GO
ALTER TABLE dbo.R_JABATAN_KOMITE_SUB_KOMITE SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.R_KEL_JABATAN_KOMITE_SUB_KOMITE ADD
	LEVEL_KOMITE char(1) NULL
GO
ALTER TABLE dbo.R_KEL_JABATAN_KOMITE_SUB_KOMITE SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
declare @CurrentUser sysname
select @CurrentUser = user_name()
execute sp_addextendedproperty 'MS_Description', 
   '1=csc; 2=sc',
   'user', @CurrentUser, 'table', 'R_KEL_JABATAN_KOMITE_SUB_KOMITE', 'column', 'TYPE_KOMITE'
go
