#!/bin/bash

rm k3pl.sql
cat 00_structure.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 00_views.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 01_data.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 02_data_pegawai.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 03_data_user_password.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 04_user_grup_observasi.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 05_user_grup_tambahan.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 06_structure_update.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 07_structure_update.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 08_data_update.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 09_structure.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 10_structure.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 11_data.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 12_structure.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 13_data.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 14_structure.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 15_structure.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 16_data.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 17_structure.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 18_data.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 19_structure.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 20_structure.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 21_structure.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 22_structure.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 23_structure.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 24_structure.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 25_data.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 26_structure.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 27_data.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 28_data.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 29_structure_data.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 30_data.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 31_structure.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 32_structure_data.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 33_data.sql >> k3pl.sql
echo "" >> k3pl.sql
cat 34_data.sql >> k3pl.sql
