delete from T_PSSR_REFERENCE;
delete from T_PSSR_KEANGGOTAAN;
delete from T_PSSR_DETAIL;
delete from T_PSSR;

delete R_ITEM_DETAIL_PSSR where ID_ITEM_DETAIL_PSSR is not null;
delete R_ITEM_PSSR where ID_ITEM_PSSR is not null;
delete R_KATEGORI_ITEM_PSSR where ID_KATEGORI_ITEM_PSSR is not null;

DBCC CHECKIDENT('R_ITEM_DETAIL_PSSR', RESEED, 0);
DBCC CHECKIDENT('R_ITEM_PSSR', RESEED, 0);
DBCC CHECKIDENT('R_KATEGORI_ITEM_PSSR', RESEED, 0);

insert into R_KATEGORI_ITEM_PSSR (NAMA_KATEGORI_ITEM_PSSR, ID_USER) values ('ORGANISASI DAN PERSONIL','1');
insert into R_ITEM_PSSR (ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_PSSR, ID_USER) values (1, 'Struktur Organisasi', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (1, 1, 'Adakah jumlah personil mencukupi', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (1, 1, 'Adakah pihak terkait sudah terlibat dan bertanggung  jawab sesuai fungsinya', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (1, 1, 'Adakah pembagian tugas di dalam tim dan dipahami', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (1, 1, 'Adakah daftar nomor telepon yang dapat dihubungi', '1');
insert into R_ITEM_PSSR (ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_PSSR, ID_USER) values (1, 'Personil Pendukung', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (2, 1, 'Adakah Petugas Pemadam Kebakaran', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (2, 1, 'Adakah Tenaga Medis', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (2, 1, 'Adakah melibatkan Petugas Keamanan', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (2, 1, 'Adakah saksi oleh perwakilan dari Migas', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (2, 1, 'Adakah PMC', '1');

insert into R_KATEGORI_ITEM_PSSR (NAMA_KATEGORI_ITEM_PSSR, ID_USER) values ('FISIK DAN PERALATAN','1');
insert into R_ITEM_PSSR (ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_PSSR, ID_USER) values (2, 'FISIK', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (3, 2, 'Apakah kondisi Test Box baik dan berfungsi', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (3, 2, 'Apakah Sistem Proteksi Katodik berfungsi dengan baik (min -850 mVolt)', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (3, 2, 'Apakah Insulating Joint pipa cabang berkondisi baik dan berfungsi', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (3, 2, 'Apakah Marker Post lengkap dan kondisinya baik', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (3, 2, 'Apakah Jembatan ada dan kondisinya baik', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (3, 2, 'Apakah Patok Gas ada dan kondisinya baik', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (3, 2, 'Apakah Venting Valve sudah dipasang sesuai dengan kebutuhan untuk gas in dan apakah kondisinya baik', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (3, 2, 'Apakah Regulator MR/S kondisinya baik dan berfungsi', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (3, 2, 'Apakah filter kondisinya baik dan berfungsi', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (3, 2, 'Apakah shut off valve kondisinya baik dan berfungsi', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (3, 2, 'Apakah relief valve MR/S sudah terpasang sesuai dengan kebutuhan', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (3, 2, 'Apakah check valve MR/S sudah terpasang dan berfungsi dengan baik', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (3, 2, 'Apakah instrumentasi (manometer, meter dan volume corrector, dll.) berfungsi dengan baik', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (3, 2, 'Apakah Insulating Joint MR/S kondisinya baik dan berfungsi', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (3, 2, 'Apakah Valve kondisinya baik (tidak bocor) dan berfungsi', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (3, 2, 'Apakah bak valve pada kondisi yang baik dan sesuai standar', '1');
insert into R_ITEM_PSSR (ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_PSSR, ID_USER) values (2, 'PERALATAN', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (4, 2, 'Adakah Multi Gas Detector tersedia dan berfungsi', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (4, 2, 'Adakah Genset tersedia dan berfungsi', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (4, 2, 'Adakah Lampu Penerangan tersedia dan berfungsi', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (4, 2, 'Adakah Pompa Air tersedia dan berfungsi', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (4, 2, 'Adakah Tool Set Non Spark tersedia dan berfungsi', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (4, 2, 'Adakah Spool set untuk venting tersedia dan berfungsi', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (4, 2, 'Adakah Exhaust Fan tersedia dan berfungsi', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (4, 2, 'Adakah Alat Komunikasi (Radio) tersedia dan berfungsi', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (4, 2, 'Adakah Pressure Gauge tersedia dan berfungsi', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (4, 2, 'Adakah Tang Ampere tersedia dan berfungsi', '1');

insert into R_KATEGORI_ITEM_PSSR (NAMA_KATEGORI_ITEM_PSSR, ID_USER) values ('FIRE DAN SAFETY','1');
insert into R_ITEM_PSSR (ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_PSSR, ID_USER) values (3, 'FIRE', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (5, 3, 'Apakah gas inlet berdekatan dengan sumber api', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (5, 3, 'Apakah gas outlet berdekatan dengan sumber api', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (5, 3, 'Apakah ada pengaman/isolasi dari sumber api', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (5, 3, 'Apakah tersedia Alat Pemadam: APAR', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (5, 3, 'Apakah tersedia Alat Pemadam: Mobil Pemadam', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (5, 3, 'Apakah sudah dilakukan koordinasi dengan otoritas pemadam kebakaran setempat: Fungsi Fire Safety Pelanggan', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (5, 3, 'Apakah sudah dilakukan koordinasi dengan otoritas pemadam kebakaran setempat: Dinas Pemadam Kebakaran', '1');
insert into R_ITEM_PSSR (ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_PSSR, ID_USER) values (3, 'SAFETY', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (6, 3, 'Apakah APD Personil tersedia', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (6, 3, 'Apakah Ambulance tersedia', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (6, 3, 'Apakah sudah disediakan rambu-rambu pengaman: Barikade', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (6, 3, 'Apakah sudah disediakan rambu-rambu pengaman: Traffic Cone', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (6, 3, 'Apakah sudah disediakan rambu-rambu pengaman: Traffic Lamp', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (6, 3, 'Apakah sudah disediakan rambu-rambu pengaman: Marker Line', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (6, 3, 'Apakah sudah disediakan rambu-rambu pengaman: Rambu Gas In', '1');

insert into R_KATEGORI_ITEM_PSSR (NAMA_KATEGORI_ITEM_PSSR, ID_USER) values ('SYSTEM','1');
insert into R_ITEM_PSSR (ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_PSSR, ID_USER) values (4, 'Apakah sudah dilakukan koordinasi dengan GMC', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (7, 4, 'Sebelum Gas In / Hottaping', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (7, 4, 'Proses Gas In / Hottaping', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (7, 4, 'Sesudah Gas In / Hottaping', '1');
insert into R_ITEM_PSSR (ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_PSSR, ID_USER) values (4, 'Apakah tersedia Dokumen Teknis sebagai berikut', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (8, 4, 'As Built Drawing / Gambar Kerja', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (8, 4, 'SAT MR/S dan Valve Report (Site Acceptance Test)', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (8, 4, 'BA Pengujian Proteksi Katodik', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (8, 4, 'Sertifikat Insulating Joint', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (8, 4, 'Sertifikat Test Valve', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (8, 4, 'Berita Acara Hydrotest', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (8, 4, 'NDT Report', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (8, 4, 'Holiday Test Report', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (8, 4, 'Berita Acara N2 Purging', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (8, 4, 'MOC', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (8, 4, 'PHA', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (8, 4, 'Wall Thickness Test dalam rangka Hot Tapping', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (8, 4, 'MIGAS Approval dalam rangka Hot Tapping', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (8, 4, 'WPS', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (8, 4, 'Sertifikat Welder', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (8, 4, 'Sertifikat pabrikan MR/S', '1');
insert into R_ITEM_PSSR (ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_PSSR, ID_USER) values (4, 'Apakah Prosedur Gas In / Hottaping tersedia', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (9, 4, 'Apakah Prosedur Gas In / Hottaping tersedia', '1');
insert into R_ITEM_PSSR (ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_PSSR, ID_USER) values (4, 'Apakah ERP (Emergency Respons Plan) tersedia', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (10, 4, 'Apakah ERP (Emergency Respons Plan) tersedia', '1');
insert into R_ITEM_PSSR (ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_PSSR, ID_USER) values (4, 'Apakah JSA (Job Safety Analisys) tersedia', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (11, 4, 'Apakah JSA (Job Safety Analisys) tersedia', '1');
insert into R_ITEM_PSSR (ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_PSSR, ID_USER) values (4, 'Apakah Izin Kerja tersedia', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (12, 4, 'Izin Kerja Panas', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (12, 4, 'Izin Kerja Dingin', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (12, 4, 'Izin Kerja Memasuki Ruang Terbatas', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (12, 4, 'Izin Kerja Galian', '1');
insert into R_ITEM_PSSR (ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_PSSR, ID_USER) values (4, 'Apakah SIMI (Surat Izin Masuk Instalasi) tersedia', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (13, 4, 'Apakah SIMI (Surat Izin Masuk Instalasi) tersedia', '1');

insert into R_KATEGORI_ITEM_PSSR (NAMA_KATEGORI_ITEM_PSSR, ID_USER) values ('ADDITIONAL CHECKLIST (diperiksa ketersediaannya dan kondisinya)','1');
insert into R_ITEM_PSSR (ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_PSSR, ID_USER) values (5, 'PROSES', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (14, 5, 'Design Basis', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (14, 5, 'P & ID', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (14, 5, 'MOC', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (14, 5, 'PHA (Process Hazard Analysis)', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (14, 5, 'ESD Function (Emergency Shut Down)', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (14, 5, 'Venting sistem', '1');
insert into R_ITEM_PSSR (ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_PSSR, ID_USER) values (5, 'MECHANICAL', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (15, 5, 'Bolt and Nut', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (15, 5, 'Tagging', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (15, 5, 'LOTO', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (15, 5, 'Piping Support', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (15, 5, 'Plat form', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (15, 5, 'Tangga', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (15, 5, 'Cat Pipa', '1');
insert into R_ITEM_PSSR (ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_PSSR, ID_USER) values (5, 'ELECTRICAL', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (16, 5, 'Cable Tray', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (16, 5, 'Junction Box', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (16, 5, 'Grounding', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (16, 5, 'Wiring Diagram', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (16, 5, 'Wiring system ( Instrumentation and Electrical )', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (16, 5, 'Cable Gland', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (16, 5, 'Lighting', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (16, 5, 'Lightning Protection', '1');
insert into R_ITEM_PSSR (ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_PSSR, ID_USER) values (5, 'CIVIL', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (17, 5, 'Pondasi', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (17, 5, 'Bak Valve', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (17, 5, 'Road (Escape Path)', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (17, 5, 'Gate / Door', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (17, 5, 'Muster Point', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (17, 5, 'Lighting Protection', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (17, 5, 'Kios / Rumah MRS', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (17, 5, 'Bangunan', '1');

insert into R_KATEGORI_ITEM_PSSR (NAMA_KATEGORI_ITEM_PSSR, ID_USER) values ('INSTALASI PELANGGAN','1');
insert into R_ITEM_PSSR (ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_PSSR, ID_USER) values (6, 'Apakah Pelanggan mempunyai PSSR', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (18, 6, 'Apakah Pelanggan mempunyai PSSR', '1');
insert into R_ITEM_PSSR (ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_PSSR, ID_USER) values (6, 'Apakah Prosedur Gas In tersedia', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (19, 6, 'Apakah Prosedur Gas In tersedia', '1');
insert into R_ITEM_PSSR (ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_PSSR, ID_USER) values (6, 'Apakah Prosedur ERP tersedia', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (20, 6, 'Apakah Prosedur ERP tersedia', '1');
insert into R_ITEM_PSSR (ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_PSSR, ID_USER) values (6, 'Apakah JSA (Job Safety Analysis) tersedia', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (21, 6, 'Apakah JSA (Job Safety Analysis) tersedia', '1');
insert into R_ITEM_PSSR (ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_PSSR, ID_USER) values (6, 'Apakah Dokumen Teknis tersedia', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (22, 6, 'Berita Acara Pemeriksaan Material', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (22, 6, 'Laporan Harian, Mingguan, Bulanan', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (22, 6, 'NDT Report', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (22, 6, 'Berita Acara Pengujian Ball Valve', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (22, 6, 'Berita Acara Pengetesan Pipa Instalasi', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (22, 6, 'Berita Acara Flushing', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (22, 6, 'Berita Acara Pengisian Nitrogen', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (22, 6, 'As Built Drawing', '1');
insert into R_ITEM_PSSR (ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_PSSR, ID_USER) values (6, 'Apakah sudah tersedia peralatan Gas', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (23, 6, 'Peralatan dual Fuel System', '1');
insert into R_ITEM_DETAIL_PSSR (ID_ITEM_PSSR, ID_KATEGORI_ITEM_PSSR, NAMA_ITEM_DETAIL_PSSR, ID_USER) values (23, 6, 'Peralatan Single Fuel System', '1');
